version: '3'
services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
      #- "5000:5000"
    #volumes:
      #- /tmp/log.txt:/tmp/log.txt
     # - ./:/app
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
